stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: fastapi-ci-cd-app:latest
  CONTAINER_NAME: fastapi-app-container


build:
  stage: build
  script:
    - echo "Building Docker Image..."
    - docker build -t $DOCKER_IMAGE .
  artifacts:
    paths:
      - Dockerfile
  only:
    - main


test:
  stage: test
  script:
    - echo "Setting up virtual environment..."
    - python3 -m venv venv             
    - source venv/bin/activate         
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running tests..."
    - venv/bin/pytest --rootdir=.                 
  only:
    - main


deploy:
  stage: deploy
  script:
    - echo "Stopping and removing any existing container..."
    - docker rm -f $CONTAINER_NAME || true
    - echo "Deploying Application..."
    - docker run -d --name $CONTAINER_NAME -p 8000:8000 $DOCKER_IMAGE
    - echo "Application deployed successfully and is running on http://localhost:8000"
  only:
    - main